### ISSUE TITLE
Panics for scales less than 48

### ISSUE THREAD

**Issue by rythmkraze** [nullboundary/glfont#1]
The example code panics upon setting font scale to any value less than 48.

`panic: reflect: slice index out of range`

**Comment by nullboundary** [comment]
Hi rythmkraze,

Thanks for finding this. Its been fixed. The problem was empty glyphs textures for fonts smaller than 48 had a width/height smaller than 1 (decimal) which was being truncated to 0.  So gl would panic because of the 0 by 0 glyph texture. 

Let me know if you have any more problems.

**Comment by rythmkraze** [comment]
Thanks :)
