### ISSUE TITLE
SetColor issue

### ISSUE THREAD

**Issue by K4thos** [nullboundary/glfont#6]
I'm testing your library (btw. great work) and it looks like SetColor function doesn't have any effect, even if I use your Example code without any other modifications. For example after changing "font.SetColor(1.0, 1.0, 1.0, 1.0)" to font.SetColor(20.0, 255.0, 100.0, 1.0) the Example code still renders the text in white color. Help would be appreciated.

edit: alpha parameter works, only r, g, b parameters are problematic.

**Comment by nullboundary** [comment]
Hi K4thos,

Thanks! 
While there could be a problem. Could you try setting the color as a ranges between 0.0-1.0 instead of 0-255? Give it a try, I am pretty sure that was the intended range of values for colors. If the problem still prevails I can look into it more.

**Comment by K4thos** [comment]
You're right. I'm so used to r,g,b 0-255 range that I didn't even think about different range. Thank you very much for fast reply and sorry for false alarm.
